#!/opt/apps/ruby/ruby/bin/ruby

def wait_until(timeout)
  max, attempt = 10, 1

  while max >= attempt do
    puts attempt
    attempt += 1
    puts yield
    if !yield
      break
    end
  end
end

wait_until(10) do
  false
end
