#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class VersionDescriptor
  include ::Thrift::Struct, ::Thrift::Struct_Union
  VERSION = 1
  TIMESTAMP = 2
  URL = 3
  FILENAME = 4

  FIELDS = {
    VERSION => {:type => ::Thrift::Types::STRING, :name => 'version'},
    TIMESTAMP => {:type => ::Thrift::Types::I64, :name => 'timestamp'},
    URL => {:type => ::Thrift::Types::STRING, :name => 'url'},
    FILENAME => {:type => ::Thrift::Types::STRING, :name => 'filename'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

